name: "[Workflow] Service Account Automation"

on:
  workflow_dispatch:
    inputs:
      CompanyName:
        description: 'Name of the Company who will maintain the service account.'
        required: true
        default: ''
      DemandNumber:
        description: 'Demand Number.'
        required: true
        default: ''
      Department:
        description: 'Department for the service account.'
        required: true
        default: ''
      SvcAccountDisplayName:
        description: 'Service Account Display Name in the format svc_<department_initials>_<team_initials>-<functional_use_name>'
        required: true
        default: ''
      Tenant:
        description: 'DEVL, NLE, LIVE'
        required: true
        default: ''
      ToRecipient:
        description: 'The email address of the Owner of the service account. This address will be sent the username and email address of the service account.'
        required: true
        default: ''

jobs:
  run-powershell-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: |
        pwsh ./ServiceAccountAutomation/ServiceAccountAutomation.ps1 -CompanyName ${{ github.event.inputs.CompanyName }} -DemandNumber ${{ github.event.inputs.DemandNumber }} -Department ${{ github.event.inputs.Department }} -SvcAccountDisplayName ${{ github.event.inputs.SvcAccountDisplayName }} -ToRecipient ${{ github.event.inputs.ToRecipient }}
