name: "[Workflow] Service Account Automation"

on:
  workflow_dispatch:
    inputs:
      CompanyName:
        description: 'Name of the Company who will maintain the service account.'
        required: true
        default: ''
      DemandNumber:
        description: 'Demand Number.'
        required: true
        default: ''
      Department:
        description: 'Department for the service account.'
        required: true
        default: ''
      SvcAccountDisplayName:
        description: 'Service Account Display Name in the format svc_<department_initials>_<team_initials>-<functional_use_name>'
        required: true
        default: ''
      Tenant:
        description: 'Please select an Envrioment to deploy to.'
        required: true
        options:
          - DEVL
          - NLE
          - LIVE
      ToRecipient:
        description: 'The email address of the Owner of the service account. This address will be sent the username and email address of the service account.'
        required: true
        default: ''

permissions:
  contents: read
  id-token: write
  security-events: write
  pull-requests: write
  issues: write


jobs:
  run-powershell-script:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.Tenant }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        client-id: ${{ secrets.ARM_CLIENT_ID }}

    - name: Run PowerShell script
      run: |
        pwsh ./ServiceAccountAutomation/ServiceAccountAutomation.ps1 -CompanyName ${{ github.event.inputs.CompanyName }} -DemandNumber ${{ github.event.inputs.DemandNumber }} -Department ${{ github.event.inputs.Department }} -SvcAccountDisplayName ${{ github.event.inputs.SvcAccountDisplayName }} -ToRecipient ${{ github.event.inputs.ToRecipient }}
